using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CuaHangDAL
{
	/// <summary>
	/// Strongly-typed collection for the ChiTietSp class.
	/// </summary>
    [Serializable]
	public partial class ChiTietSpCollection : ActiveList<ChiTietSp, ChiTietSpCollection>
	{	   
		public ChiTietSpCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>ChiTietSpCollection</returns>
		public ChiTietSpCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                ChiTietSp o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the ChiTietSp table.
	/// </summary>
	[Serializable]
	public partial class ChiTietSp : ActiveRecord<ChiTietSp>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public ChiTietSp()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public ChiTietSp(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public ChiTietSp(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public ChiTietSp(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("ChiTietSp", TableType.Table, DataService.GetInstance("AdventureWorks"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarMachitietsp = new TableSchema.TableColumn(schema);
				colvarMachitietsp.ColumnName = "machitietsp";
				colvarMachitietsp.DataType = DbType.Int32;
				colvarMachitietsp.MaxLength = 0;
				colvarMachitietsp.AutoIncrement = true;
				colvarMachitietsp.IsNullable = false;
				colvarMachitietsp.IsPrimaryKey = true;
				colvarMachitietsp.IsForeignKey = false;
				colvarMachitietsp.IsReadOnly = false;
				colvarMachitietsp.DefaultSetting = @"";
				colvarMachitietsp.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMachitietsp);
				
				TableSchema.TableColumn colvarMasp = new TableSchema.TableColumn(schema);
				colvarMasp.ColumnName = "Masp";
				colvarMasp.DataType = DbType.Int32;
				colvarMasp.MaxLength = 0;
				colvarMasp.AutoIncrement = false;
				colvarMasp.IsNullable = true;
				colvarMasp.IsPrimaryKey = false;
				colvarMasp.IsForeignKey = true;
				colvarMasp.IsReadOnly = false;
				colvarMasp.DefaultSetting = @"";
				
					colvarMasp.ForeignKeyTableName = "SanPham";
				schema.Columns.Add(colvarMasp);
				
				TableSchema.TableColumn colvarMaNCC = new TableSchema.TableColumn(schema);
				colvarMaNCC.ColumnName = "MaNCC";
				colvarMaNCC.DataType = DbType.Int32;
				colvarMaNCC.MaxLength = 0;
				colvarMaNCC.AutoIncrement = false;
				colvarMaNCC.IsNullable = true;
				colvarMaNCC.IsPrimaryKey = false;
				colvarMaNCC.IsForeignKey = true;
				colvarMaNCC.IsReadOnly = false;
				colvarMaNCC.DefaultSetting = @"";
				
					colvarMaNCC.ForeignKeyTableName = "NhaCungCap";
				schema.Columns.Add(colvarMaNCC);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["AdventureWorks"].AddSchema("ChiTietSp",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Machitietsp")]
		[Bindable(true)]
		public int Machitietsp 
		{
			get { return GetColumnValue<int>(Columns.Machitietsp); }
			set { SetColumnValue(Columns.Machitietsp, value); }
		}
		  
		[XmlAttribute("Masp")]
		[Bindable(true)]
		public int? Masp 
		{
			get { return GetColumnValue<int?>(Columns.Masp); }
			set { SetColumnValue(Columns.Masp, value); }
		}
		  
		[XmlAttribute("MaNCC")]
		[Bindable(true)]
		public int? MaNCC 
		{
			get { return GetColumnValue<int?>(Columns.MaNCC); }
			set { SetColumnValue(Columns.MaNCC, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a NhaCungCap ActiveRecord object related to this ChiTietSp
		/// 
		/// </summary>
		public CuaHangDAL.NhaCungCap NhaCungCap
		{
			get { return CuaHangDAL.NhaCungCap.FetchByID(this.MaNCC); }
			set { SetColumnValue("MaNCC", value.MaNCC); }
		}
		
		
		/// <summary>
		/// Returns a SanPham ActiveRecord object related to this ChiTietSp
		/// 
		/// </summary>
		public CuaHangDAL.SanPham SanPham
		{
			get { return CuaHangDAL.SanPham.FetchByID(this.Masp); }
			set { SetColumnValue("Masp", value.Masp); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int? varMasp,int? varMaNCC)
		{
			ChiTietSp item = new ChiTietSp();
			
			item.Masp = varMasp;
			
			item.MaNCC = varMaNCC;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varMachitietsp,int? varMasp,int? varMaNCC)
		{
			ChiTietSp item = new ChiTietSp();
			
				item.Machitietsp = varMachitietsp;
			
				item.Masp = varMasp;
			
				item.MaNCC = varMaNCC;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn MachitietspColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn MaspColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn MaNCCColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Machitietsp = @"machitietsp";
			 public static string Masp = @"Masp";
			 public static string MaNCC = @"MaNCC";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
