using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CuaHangDAL
{
    /// <summary>
    /// Controller class for ChiTietSp
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ChiTietSpController
    {
        // Preload our schema..
        ChiTietSp thisSchemaLoad = new ChiTietSp();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ChiTietSpCollection FetchAll()
        {
            ChiTietSpCollection coll = new ChiTietSpCollection();
            Query qry = new Query(ChiTietSp.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ChiTietSpCollection FetchByID(object Machitietsp)
        {
            ChiTietSpCollection coll = new ChiTietSpCollection().Where("machitietsp", Machitietsp).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ChiTietSpCollection FetchByQuery(Query qry)
        {
            ChiTietSpCollection coll = new ChiTietSpCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Machitietsp)
        {
            return (ChiTietSp.Delete(Machitietsp) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Machitietsp)
        {
            return (ChiTietSp.Destroy(Machitietsp) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public ChiTietSp Insert(ChiTietSp item)
	    {
            item.Save(UserName);
            return item;
        }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public ChiTietSp Update(ChiTietSp item2)
	    {
		    ChiTietSp item = new ChiTietSp();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Machitietsp = item2.Machitietsp;
				
			item.Masp = item2.Masp;
				
			item.MaNCC = item2.MaNCC;
				
	        item.Save(UserName);
            return item;
	    }
    }
}
