using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CuaHangDAL
{
    /// <summary>
    /// Controller class for CTHD
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class CthdController
    {
        // Preload our schema..
        Cthd thisSchemaLoad = new Cthd();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CthdCollection FetchAll()
        {
            CthdCollection coll = new CthdCollection();
            Query qry = new Query(Cthd.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CthdCollection FetchByID(object MaCTHd)
        {
            CthdCollection coll = new CthdCollection().Where("MaCT_HD", MaCTHd).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public CthdCollection FetchByQuery(Query qry)
        {
            CthdCollection coll = new CthdCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MaCTHd)
        {
            return (Cthd.Delete(MaCTHd) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MaCTHd)
        {
            return (Cthd.Destroy(MaCTHd) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public Cthd Insert(Cthd item)
	    {
	 
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public Cthd Update(Cthd item2)
	    {
		    Cthd item = new Cthd();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.MaCTHd = item2.MaCTHd;
				
			item.MaHD = item2.MaHD;
				
			item.MaSp = item2.MaSp;
				
			item.TenSP = item2.TenSP;
				
			item.SoLuong = item2.SoLuong;
				
			item.DonGiaBan = item2.DonGiaBan;
				
	        item.Save(UserName);
            return item;
	    }
    }
}
