using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CuaHangDAL
{
    /// <summary>
    /// Controller class for CTPN
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class CtpnController
    {
        // Preload our schema..
        Ctpn thisSchemaLoad = new Ctpn();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CtpnCollection FetchAll()
        {
            CtpnCollection coll = new CtpnCollection();
            Query qry = new Query(Ctpn.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CtpnCollection FetchByID(object MaCTPn)
        {
            CtpnCollection coll = new CtpnCollection().Where("MaCT_PN", MaCTPn).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public CtpnCollection FetchByQuery(Query qry)
        {
            CtpnCollection coll = new CtpnCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MaCTPn)
        {
            return (Ctpn.Delete(MaCTPn) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MaCTPn)
        {
            return (Ctpn.Destroy(MaCTPn) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public Ctpn Insert(Ctpn item)
	    {
		
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public Ctpn Update(Ctpn item2)
	    {
		    Ctpn item = new Ctpn();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.MaCTPn = item2.MaCTPn;
				
			item.MaPN = item2.MaPN;
				
			item.MaSp = item2.MaSp;
				
			item.TenSP = item2.TenSP;
				
			item.SoLuong = item2.SoLuong;
				
			item.DonGiaNhap = item2.DonGiaNhap;
				
	        item.Save(UserName);
            return item;
	    }
    }
}
