using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CuaHangDAL
{
    /// <summary>
    /// Controller class for DanHMuc
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DanHMucController
    {
        // Preload our schema..
        DanHMuc thisSchemaLoad = new DanHMuc();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DanHMucCollection FetchAll()
        {
            DanHMucCollection coll = new DanHMucCollection();
            Query qry = new Query(DanHMuc.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DanHMucCollection FetchByID(object MaDM)
        {
            DanHMucCollection coll = new DanHMucCollection().Where("MaDM", MaDM).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DanHMucCollection FetchByQuery(Query qry)
        {
            DanHMucCollection coll = new DanHMucCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MaDM)
        {
            return (DanHMuc.Delete(MaDM) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MaDM)
        {
            return (DanHMuc.Destroy(MaDM) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public DanHMuc Insert(DanHMuc item)
	    {
           
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public DanHMuc Update(DanHMuc item2)
	    {
		    DanHMuc item = new DanHMuc();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.MaDM = item2.MaDM;
				
			item.TenDM = item2.TenDM;
				
			item.Ngaycapnhap = item2.Ngaycapnhap;
				
			item.MaNVchinhsua = item2.MaNVchinhsua;
				
			item.Status = item2.Status;
				
	        item.Save(UserName);
            return item;
	    }
    }
}
