using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CuaHangDAL
{
	/// <summary>
	/// Strongly-typed collection for the KhachHang class.
	/// </summary>
    [Serializable]
	public partial class KhachHangCollection : ActiveList<KhachHang, KhachHangCollection>
	{	   
		public KhachHangCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>KhachHangCollection</returns>
		public KhachHangCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                KhachHang o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the KhachHang table.
	/// </summary>
	[Serializable]
	public partial class KhachHang : ActiveRecord<KhachHang>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public KhachHang()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public KhachHang(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public KhachHang(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public KhachHang(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("KhachHang", TableType.Table, DataService.GetInstance("AdventureWorks"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarMaKh = new TableSchema.TableColumn(schema);
				colvarMaKh.ColumnName = "MaKh";
				colvarMaKh.DataType = DbType.Int32;
				colvarMaKh.MaxLength = 0;
				colvarMaKh.AutoIncrement = true;
				colvarMaKh.IsNullable = false;
				colvarMaKh.IsPrimaryKey = true;
				colvarMaKh.IsForeignKey = false;
				colvarMaKh.IsReadOnly = false;
				colvarMaKh.DefaultSetting = @"";
				colvarMaKh.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMaKh);
				
				TableSchema.TableColumn colvarTenKH = new TableSchema.TableColumn(schema);
				colvarTenKH.ColumnName = "TenKH";
				colvarTenKH.DataType = DbType.String;
				colvarTenKH.MaxLength = 255;
				colvarTenKH.AutoIncrement = false;
				colvarTenKH.IsNullable = true;
				colvarTenKH.IsPrimaryKey = false;
				colvarTenKH.IsForeignKey = false;
				colvarTenKH.IsReadOnly = false;
				colvarTenKH.DefaultSetting = @"";
				colvarTenKH.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTenKH);
				
				TableSchema.TableColumn colvarDiaChi = new TableSchema.TableColumn(schema);
				colvarDiaChi.ColumnName = "DiaChi";
				colvarDiaChi.DataType = DbType.String;
				colvarDiaChi.MaxLength = 255;
				colvarDiaChi.AutoIncrement = false;
				colvarDiaChi.IsNullable = true;
				colvarDiaChi.IsPrimaryKey = false;
				colvarDiaChi.IsForeignKey = false;
				colvarDiaChi.IsReadOnly = false;
				colvarDiaChi.DefaultSetting = @"";
				colvarDiaChi.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDiaChi);
				
				TableSchema.TableColumn colvarSdt = new TableSchema.TableColumn(schema);
				colvarSdt.ColumnName = "sdt";
				colvarSdt.DataType = DbType.AnsiString;
				colvarSdt.MaxLength = 12;
				colvarSdt.AutoIncrement = false;
				colvarSdt.IsNullable = true;
				colvarSdt.IsPrimaryKey = false;
				colvarSdt.IsForeignKey = false;
				colvarSdt.IsReadOnly = false;
				colvarSdt.DefaultSetting = @"";
				colvarSdt.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSdt);
				
				TableSchema.TableColumn colvarEmail = new TableSchema.TableColumn(schema);
				colvarEmail.ColumnName = "Email";
				colvarEmail.DataType = DbType.AnsiString;
				colvarEmail.MaxLength = 50;
				colvarEmail.AutoIncrement = false;
				colvarEmail.IsNullable = true;
				colvarEmail.IsPrimaryKey = false;
				colvarEmail.IsForeignKey = false;
				colvarEmail.IsReadOnly = false;
				colvarEmail.DefaultSetting = @"";
				colvarEmail.ForeignKeyTableName = "";
				schema.Columns.Add(colvarEmail);
				
				TableSchema.TableColumn colvarCmd = new TableSchema.TableColumn(schema);
				colvarCmd.ColumnName = "CMD";
				colvarCmd.DataType = DbType.AnsiString;
				colvarCmd.MaxLength = 15;
				colvarCmd.AutoIncrement = false;
				colvarCmd.IsNullable = true;
				colvarCmd.IsPrimaryKey = false;
				colvarCmd.IsForeignKey = false;
				colvarCmd.IsReadOnly = false;
				colvarCmd.DefaultSetting = @"";
				colvarCmd.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCmd);
				
				TableSchema.TableColumn colvarDiemso = new TableSchema.TableColumn(schema);
				colvarDiemso.ColumnName = "diemso";
				colvarDiemso.DataType = DbType.Int32;
				colvarDiemso.MaxLength = 0;
				colvarDiemso.AutoIncrement = false;
				colvarDiemso.IsNullable = true;
				colvarDiemso.IsPrimaryKey = false;
				colvarDiemso.IsForeignKey = false;
				colvarDiemso.IsReadOnly = false;
				colvarDiemso.DefaultSetting = @"";
				colvarDiemso.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDiemso);
				
				TableSchema.TableColumn colvarMaTV = new TableSchema.TableColumn(schema);
				colvarMaTV.ColumnName = "MaTV";
				colvarMaTV.DataType = DbType.Int32;
				colvarMaTV.MaxLength = 0;
				colvarMaTV.AutoIncrement = false;
				colvarMaTV.IsNullable = true;
				colvarMaTV.IsPrimaryKey = false;
				colvarMaTV.IsForeignKey = true;
				colvarMaTV.IsReadOnly = false;
				colvarMaTV.DefaultSetting = @"";
				
					colvarMaTV.ForeignKeyTableName = "LoaiThanhVien";
				schema.Columns.Add(colvarMaTV);
				
				TableSchema.TableColumn colvarMaTk = new TableSchema.TableColumn(schema);
				colvarMaTk.ColumnName = "MaTk";
				colvarMaTk.DataType = DbType.Int32;
				colvarMaTk.MaxLength = 0;
				colvarMaTk.AutoIncrement = false;
				colvarMaTk.IsNullable = true;
				colvarMaTk.IsPrimaryKey = false;
				colvarMaTk.IsForeignKey = true;
				colvarMaTk.IsReadOnly = false;
				colvarMaTk.DefaultSetting = @"";
				
					colvarMaTk.ForeignKeyTableName = "TaiKhoan";
				schema.Columns.Add(colvarMaTk);
				
				TableSchema.TableColumn colvarNgaycapnhap = new TableSchema.TableColumn(schema);
				colvarNgaycapnhap.ColumnName = "ngaycapnhap";
				colvarNgaycapnhap.DataType = DbType.DateTime;
				colvarNgaycapnhap.MaxLength = 0;
				colvarNgaycapnhap.AutoIncrement = false;
				colvarNgaycapnhap.IsNullable = true;
				colvarNgaycapnhap.IsPrimaryKey = false;
				colvarNgaycapnhap.IsForeignKey = false;
				colvarNgaycapnhap.IsReadOnly = false;
				colvarNgaycapnhap.DefaultSetting = @"";
				colvarNgaycapnhap.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgaycapnhap);
				
				TableSchema.TableColumn colvarMaNVchinhsua = new TableSchema.TableColumn(schema);
				colvarMaNVchinhsua.ColumnName = "MaNVchinhsua";
				colvarMaNVchinhsua.DataType = DbType.Int32;
				colvarMaNVchinhsua.MaxLength = 0;
				colvarMaNVchinhsua.AutoIncrement = false;
				colvarMaNVchinhsua.IsNullable = true;
				colvarMaNVchinhsua.IsPrimaryKey = false;
				colvarMaNVchinhsua.IsForeignKey = true;
				colvarMaNVchinhsua.IsReadOnly = false;
				colvarMaNVchinhsua.DefaultSetting = @"";
				
					colvarMaNVchinhsua.ForeignKeyTableName = "NhanVien";
				schema.Columns.Add(colvarMaNVchinhsua);
				
				TableSchema.TableColumn colvarStatus = new TableSchema.TableColumn(schema);
				colvarStatus.ColumnName = "status";
				colvarStatus.DataType = DbType.String;
				colvarStatus.MaxLength = 50;
				colvarStatus.AutoIncrement = false;
				colvarStatus.IsNullable = false;
				colvarStatus.IsPrimaryKey = false;
				colvarStatus.IsForeignKey = false;
				colvarStatus.IsReadOnly = false;
				
						colvarStatus.DefaultSetting = @"('trong')";
				colvarStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarStatus);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["AdventureWorks"].AddSchema("KhachHang",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("MaKh")]
		[Bindable(true)]
		public int MaKh 
		{
			get { return GetColumnValue<int>(Columns.MaKh); }
			set { SetColumnValue(Columns.MaKh, value); }
		}
		  
		[XmlAttribute("TenKH")]
		[Bindable(true)]
		public string TenKH 
		{
			get { return GetColumnValue<string>(Columns.TenKH); }
			set { SetColumnValue(Columns.TenKH, value); }
		}
		  
		[XmlAttribute("DiaChi")]
		[Bindable(true)]
		public string DiaChi 
		{
			get { return GetColumnValue<string>(Columns.DiaChi); }
			set { SetColumnValue(Columns.DiaChi, value); }
		}
		  
		[XmlAttribute("Sdt")]
		[Bindable(true)]
		public string Sdt 
		{
			get { return GetColumnValue<string>(Columns.Sdt); }
			set { SetColumnValue(Columns.Sdt, value); }
		}
		  
		[XmlAttribute("Email")]
		[Bindable(true)]
		public string Email 
		{
			get { return GetColumnValue<string>(Columns.Email); }
			set { SetColumnValue(Columns.Email, value); }
		}
		  
		[XmlAttribute("Cmd")]
		[Bindable(true)]
		public string Cmd 
		{
			get { return GetColumnValue<string>(Columns.Cmd); }
			set { SetColumnValue(Columns.Cmd, value); }
		}
		  
		[XmlAttribute("Diemso")]
		[Bindable(true)]
		public int? Diemso 
		{
			get { return GetColumnValue<int?>(Columns.Diemso); }
			set { SetColumnValue(Columns.Diemso, value); }
		}
		  
		[XmlAttribute("MaTV")]
		[Bindable(true)]
		public int? MaTV 
		{
			get { return GetColumnValue<int?>(Columns.MaTV); }
			set { SetColumnValue(Columns.MaTV, value); }
		}
		  
		[XmlAttribute("MaTk")]
		[Bindable(true)]
		public int? MaTk 
		{
			get { return GetColumnValue<int?>(Columns.MaTk); }
			set { SetColumnValue(Columns.MaTk, value); }
		}
		  
		[XmlAttribute("Ngaycapnhap")]
		[Bindable(true)]
		public DateTime? Ngaycapnhap 
		{
			get { return GetColumnValue<DateTime?>(Columns.Ngaycapnhap); }
			set { SetColumnValue(Columns.Ngaycapnhap, value); }
		}
		  
		[XmlAttribute("MaNVchinhsua")]
		[Bindable(true)]
		public int? MaNVchinhsua 
		{
			get { return GetColumnValue<int?>(Columns.MaNVchinhsua); }
			set { SetColumnValue(Columns.MaNVchinhsua, value); }
		}
		  
		[XmlAttribute("Status")]
		[Bindable(true)]
		public string Status 
		{
			get { return GetColumnValue<string>(Columns.Status); }
			set { SetColumnValue(Columns.Status, value); }
		}
		
		#endregion
		
		
		#region PrimaryKey Methods		
		
        protected override void SetPrimaryKey(object oValue)
        {
            base.SetPrimaryKey(oValue);
            
            SetPKValues();
        }
        
		
		public CuaHangDAL.HdCollection HdRecords()
		{
			return new CuaHangDAL.HdCollection().Where(Hd.Columns.MaKH, MaKh).Load();
		}
		#endregion
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a NhanVien ActiveRecord object related to this KhachHang
		/// 
		/// </summary>
		public CuaHangDAL.NhanVien NhanVien
		{
			get { return CuaHangDAL.NhanVien.FetchByID(this.MaNVchinhsua); }
			set { SetColumnValue("MaNVchinhsua", value.MaNV); }
		}
		
		
		/// <summary>
		/// Returns a LoaiThanhVien ActiveRecord object related to this KhachHang
		/// 
		/// </summary>
		public CuaHangDAL.LoaiThanhVien LoaiThanhVien
		{
			get { return CuaHangDAL.LoaiThanhVien.FetchByID(this.MaTV); }
			set { SetColumnValue("MaTV", value.MaLoaitv); }
		}
		
		
		/// <summary>
		/// Returns a TaiKhoan ActiveRecord object related to this KhachHang
		/// 
		/// </summary>
		public CuaHangDAL.TaiKhoan TaiKhoan
		{
			get { return CuaHangDAL.TaiKhoan.FetchByID(this.MaTk); }
			set { SetColumnValue("MaTk", value.MaTK); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varTenKH,string varDiaChi,string varSdt,string varEmail,string varCmd,int? varDiemso,int? varMaTV,int? varMaTk,DateTime? varNgaycapnhap,int? varMaNVchinhsua,string varStatus)
		{
			KhachHang item = new KhachHang();
			
			item.TenKH = varTenKH;
			
			item.DiaChi = varDiaChi;
			
			item.Sdt = varSdt;
			
			item.Email = varEmail;
			
			item.Cmd = varCmd;
			
			item.Diemso = varDiemso;
			
			item.MaTV = varMaTV;
			
			item.MaTk = varMaTk;
			
			item.Ngaycapnhap = varNgaycapnhap;
			
			item.MaNVchinhsua = varMaNVchinhsua;
			
			item.Status = varStatus;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varMaKh,string varTenKH,string varDiaChi,string varSdt,string varEmail,string varCmd,int? varDiemso,int? varMaTV,int? varMaTk,DateTime? varNgaycapnhap,int? varMaNVchinhsua,string varStatus)
		{
			KhachHang item = new KhachHang();
			
				item.MaKh = varMaKh;
			
				item.TenKH = varTenKH;
			
				item.DiaChi = varDiaChi;
			
				item.Sdt = varSdt;
			
				item.Email = varEmail;
			
				item.Cmd = varCmd;
			
				item.Diemso = varDiemso;
			
				item.MaTV = varMaTV;
			
				item.MaTk = varMaTk;
			
				item.Ngaycapnhap = varNgaycapnhap;
			
				item.MaNVchinhsua = varMaNVchinhsua;
			
				item.Status = varStatus;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn MaKhColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn TenKHColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn DiaChiColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn SdtColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn EmailColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn CmdColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn DiemsoColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn MaTVColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn MaTkColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn NgaycapnhapColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn MaNVchinhsuaColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn StatusColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string MaKh = @"MaKh";
			 public static string TenKH = @"TenKH";
			 public static string DiaChi = @"DiaChi";
			 public static string Sdt = @"sdt";
			 public static string Email = @"Email";
			 public static string Cmd = @"CMD";
			 public static string Diemso = @"diemso";
			 public static string MaTV = @"MaTV";
			 public static string MaTk = @"MaTk";
			 public static string Ngaycapnhap = @"ngaycapnhap";
			 public static string MaNVchinhsua = @"MaNVchinhsua";
			 public static string Status = @"status";
						
		}
		#endregion
		
		#region Update PK Collections
		
        public void SetPKValues()
        {
}
        #endregion
    
        #region Deep Save
		
        public void DeepSave()
        {
            Save();
            
}
        #endregion
	}
}
