using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CuaHangDAL
{
    /// <summary>
    /// Controller class for LoaiThanhVien
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class LoaiThanhVienController
    {
        // Preload our schema..
        LoaiThanhVien thisSchemaLoad = new LoaiThanhVien();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public LoaiThanhVienCollection FetchAll()
        {
            LoaiThanhVienCollection coll = new LoaiThanhVienCollection();
            Query qry = new Query(LoaiThanhVien.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public LoaiThanhVienCollection FetchByID(object MaLoaitv)
        {
            LoaiThanhVienCollection coll = new LoaiThanhVienCollection().Where("MaLoaitv", MaLoaitv).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public LoaiThanhVienCollection FetchByQuery(Query qry)
        {
            LoaiThanhVienCollection coll = new LoaiThanhVienCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MaLoaitv)
        {
            return (LoaiThanhVien.Delete(MaLoaitv) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MaLoaitv)
        {
            return (LoaiThanhVien.Destroy(MaLoaitv) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public LoaiThanhVien Insert(LoaiThanhVien item)
	    {

	    
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public LoaiThanhVien Update(LoaiThanhVien item2)
	    {
		    LoaiThanhVien item = new LoaiThanhVien();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.MaLoaitv = item2.MaLoaitv;
				
			item.TenLoai = item2.TenLoai;
				
			item.Uudai = item2.Uudai;
				
			item.Ngaycapnhap = item2.Ngaycapnhap;
				
			item.MaNVchinhsua = item2.MaNVchinhsua;
				
	        item.Save(UserName);
            return item;
	    }
    }
}
