using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CuaHangDAL
{
    /// <summary>
    /// Controller class for NhaCungCap
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class NhaCungCapController
    {
        // Preload our schema..
        NhaCungCap thisSchemaLoad = new NhaCungCap();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public NhaCungCapCollection FetchAll()
        {
            NhaCungCapCollection coll = new NhaCungCapCollection();
            Query qry = new Query(NhaCungCap.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public NhaCungCapCollection FetchByID(object MaNCC)
        {
            NhaCungCapCollection coll = new NhaCungCapCollection().Where("MaNCC", MaNCC).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public NhaCungCapCollection FetchByQuery(Query qry)
        {
            NhaCungCapCollection coll = new NhaCungCapCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MaNCC)
        {
            return (NhaCungCap.Delete(MaNCC) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MaNCC)
        {
            return (NhaCungCap.Destroy(MaNCC) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public NhaCungCap Insert(NhaCungCap item)
	    {
		   
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public NhaCungCap Update(NhaCungCap item2)
	    {
		    NhaCungCap item = new NhaCungCap();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.MaNCC = item2.MaNCC;
				
			item.TenNCC = item2.TenNCC;
				
			item.Diachi = item2.Diachi;
				
			item.Email = item2.Email;
				
			item.Ngaycapnhap = item2.Ngaycapnhap;
				
			item.MaNVchinhsua = item2.MaNVchinhsua;
				
			item.Status = item2.Status;
				
	        item.Save(UserName);
            return item;
	    }
    }
}
