using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CuaHangDAL
{
	/// <summary>
	/// Strongly-typed collection for the NhanVien class.
	/// </summary>
    [Serializable]
	public partial class NhanVienCollection : ActiveList<NhanVien, NhanVienCollection>
	{	   
		public NhanVienCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>NhanVienCollection</returns>
		public NhanVienCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                NhanVien o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the NhanVien table.
	/// </summary>
	[Serializable]
	public partial class NhanVien : ActiveRecord<NhanVien>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public NhanVien()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public NhanVien(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public NhanVien(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public NhanVien(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("NhanVien", TableType.Table, DataService.GetInstance("AdventureWorks"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarMaNV = new TableSchema.TableColumn(schema);
				colvarMaNV.ColumnName = "MaNV";
				colvarMaNV.DataType = DbType.Int32;
				colvarMaNV.MaxLength = 0;
				colvarMaNV.AutoIncrement = true;
				colvarMaNV.IsNullable = false;
				colvarMaNV.IsPrimaryKey = true;
				colvarMaNV.IsForeignKey = false;
				colvarMaNV.IsReadOnly = false;
				colvarMaNV.DefaultSetting = @"";
				colvarMaNV.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMaNV);
				
				TableSchema.TableColumn colvarTenNv = new TableSchema.TableColumn(schema);
				colvarTenNv.ColumnName = "TenNv";
				colvarTenNv.DataType = DbType.String;
				colvarTenNv.MaxLength = 255;
				colvarTenNv.AutoIncrement = false;
				colvarTenNv.IsNullable = true;
				colvarTenNv.IsPrimaryKey = false;
				colvarTenNv.IsForeignKey = false;
				colvarTenNv.IsReadOnly = false;
				colvarTenNv.DefaultSetting = @"";
				colvarTenNv.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTenNv);
				
				TableSchema.TableColumn colvarDiaChi = new TableSchema.TableColumn(schema);
				colvarDiaChi.ColumnName = "DiaChi";
				colvarDiaChi.DataType = DbType.String;
				colvarDiaChi.MaxLength = 255;
				colvarDiaChi.AutoIncrement = false;
				colvarDiaChi.IsNullable = true;
				colvarDiaChi.IsPrimaryKey = false;
				colvarDiaChi.IsForeignKey = false;
				colvarDiaChi.IsReadOnly = false;
				colvarDiaChi.DefaultSetting = @"";
				colvarDiaChi.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDiaChi);
				
				TableSchema.TableColumn colvarSdt = new TableSchema.TableColumn(schema);
				colvarSdt.ColumnName = "sdt";
				colvarSdt.DataType = DbType.AnsiString;
				colvarSdt.MaxLength = 12;
				colvarSdt.AutoIncrement = false;
				colvarSdt.IsNullable = true;
				colvarSdt.IsPrimaryKey = false;
				colvarSdt.IsForeignKey = false;
				colvarSdt.IsReadOnly = false;
				colvarSdt.DefaultSetting = @"";
				colvarSdt.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSdt);
				
				TableSchema.TableColumn colvarEmail = new TableSchema.TableColumn(schema);
				colvarEmail.ColumnName = "Email";
				colvarEmail.DataType = DbType.AnsiString;
				colvarEmail.MaxLength = 50;
				colvarEmail.AutoIncrement = false;
				colvarEmail.IsNullable = true;
				colvarEmail.IsPrimaryKey = false;
				colvarEmail.IsForeignKey = false;
				colvarEmail.IsReadOnly = false;
				colvarEmail.DefaultSetting = @"";
				colvarEmail.ForeignKeyTableName = "";
				schema.Columns.Add(colvarEmail);
				
				TableSchema.TableColumn colvarCmd = new TableSchema.TableColumn(schema);
				colvarCmd.ColumnName = "CMD";
				colvarCmd.DataType = DbType.AnsiString;
				colvarCmd.MaxLength = 15;
				colvarCmd.AutoIncrement = false;
				colvarCmd.IsNullable = true;
				colvarCmd.IsPrimaryKey = false;
				colvarCmd.IsForeignKey = false;
				colvarCmd.IsReadOnly = false;
				colvarCmd.DefaultSetting = @"";
				colvarCmd.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCmd);
				
				TableSchema.TableColumn colvarThamsoloinhuan = new TableSchema.TableColumn(schema);
				colvarThamsoloinhuan.ColumnName = "thamsoloinhuan";
				colvarThamsoloinhuan.DataType = DbType.Decimal;
				colvarThamsoloinhuan.MaxLength = 0;
				colvarThamsoloinhuan.AutoIncrement = false;
				colvarThamsoloinhuan.IsNullable = true;
				colvarThamsoloinhuan.IsPrimaryKey = false;
				colvarThamsoloinhuan.IsForeignKey = false;
				colvarThamsoloinhuan.IsReadOnly = false;
				colvarThamsoloinhuan.DefaultSetting = @"";
				colvarThamsoloinhuan.ForeignKeyTableName = "";
				schema.Columns.Add(colvarThamsoloinhuan);
				
				TableSchema.TableColumn colvarMaNVchinhsua = new TableSchema.TableColumn(schema);
				colvarMaNVchinhsua.ColumnName = "MaNVchinhsua";
				colvarMaNVchinhsua.DataType = DbType.Int32;
				colvarMaNVchinhsua.MaxLength = 0;
				colvarMaNVchinhsua.AutoIncrement = false;
				colvarMaNVchinhsua.IsNullable = true;
				colvarMaNVchinhsua.IsPrimaryKey = false;
				colvarMaNVchinhsua.IsForeignKey = true;
				colvarMaNVchinhsua.IsReadOnly = false;
				colvarMaNVchinhsua.DefaultSetting = @"";
				
					colvarMaNVchinhsua.ForeignKeyTableName = "NhanVien";
				schema.Columns.Add(colvarMaNVchinhsua);
				
				TableSchema.TableColumn colvarNgaycapnhap = new TableSchema.TableColumn(schema);
				colvarNgaycapnhap.ColumnName = "ngaycapnhap";
				colvarNgaycapnhap.DataType = DbType.DateTime;
				colvarNgaycapnhap.MaxLength = 0;
				colvarNgaycapnhap.AutoIncrement = false;
				colvarNgaycapnhap.IsNullable = true;
				colvarNgaycapnhap.IsPrimaryKey = false;
				colvarNgaycapnhap.IsForeignKey = false;
				colvarNgaycapnhap.IsReadOnly = false;
				colvarNgaycapnhap.DefaultSetting = @"";
				colvarNgaycapnhap.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgaycapnhap);
				
				TableSchema.TableColumn colvarMaTk = new TableSchema.TableColumn(schema);
				colvarMaTk.ColumnName = "MaTk";
				colvarMaTk.DataType = DbType.Int32;
				colvarMaTk.MaxLength = 0;
				colvarMaTk.AutoIncrement = false;
				colvarMaTk.IsNullable = true;
				colvarMaTk.IsPrimaryKey = false;
				colvarMaTk.IsForeignKey = true;
				colvarMaTk.IsReadOnly = false;
				colvarMaTk.DefaultSetting = @"";
				
					colvarMaTk.ForeignKeyTableName = "TaiKhoan";
				schema.Columns.Add(colvarMaTk);
				
				TableSchema.TableColumn colvarStatus = new TableSchema.TableColumn(schema);
				colvarStatus.ColumnName = "status";
				colvarStatus.DataType = DbType.String;
				colvarStatus.MaxLength = 50;
				colvarStatus.AutoIncrement = false;
				colvarStatus.IsNullable = false;
				colvarStatus.IsPrimaryKey = false;
				colvarStatus.IsForeignKey = false;
				colvarStatus.IsReadOnly = false;
				
						colvarStatus.DefaultSetting = @"('trong')";
				colvarStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarStatus);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["AdventureWorks"].AddSchema("NhanVien",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("MaNV")]
		[Bindable(true)]
		public int MaNV 
		{
			get { return GetColumnValue<int>(Columns.MaNV); }
			set { SetColumnValue(Columns.MaNV, value); }
		}
		  
		[XmlAttribute("TenNv")]
		[Bindable(true)]
		public string TenNv 
		{
			get { return GetColumnValue<string>(Columns.TenNv); }
			set { SetColumnValue(Columns.TenNv, value); }
		}
		  
		[XmlAttribute("DiaChi")]
		[Bindable(true)]
		public string DiaChi 
		{
			get { return GetColumnValue<string>(Columns.DiaChi); }
			set { SetColumnValue(Columns.DiaChi, value); }
		}
		  
		[XmlAttribute("Sdt")]
		[Bindable(true)]
		public string Sdt 
		{
			get { return GetColumnValue<string>(Columns.Sdt); }
			set { SetColumnValue(Columns.Sdt, value); }
		}
		  
		[XmlAttribute("Email")]
		[Bindable(true)]
		public string Email 
		{
			get { return GetColumnValue<string>(Columns.Email); }
			set { SetColumnValue(Columns.Email, value); }
		}
		  
		[XmlAttribute("Cmd")]
		[Bindable(true)]
		public string Cmd 
		{
			get { return GetColumnValue<string>(Columns.Cmd); }
			set { SetColumnValue(Columns.Cmd, value); }
		}
		  
		[XmlAttribute("Thamsoloinhuan")]
		[Bindable(true)]
		public decimal? Thamsoloinhuan 
		{
			get { return GetColumnValue<decimal?>(Columns.Thamsoloinhuan); }
			set { SetColumnValue(Columns.Thamsoloinhuan, value); }
		}
		  
		[XmlAttribute("MaNVchinhsua")]
		[Bindable(true)]
		public int? MaNVchinhsua 
		{
			get { return GetColumnValue<int?>(Columns.MaNVchinhsua); }
			set { SetColumnValue(Columns.MaNVchinhsua, value); }
		}
		  
		[XmlAttribute("Ngaycapnhap")]
		[Bindable(true)]
		public DateTime? Ngaycapnhap 
		{
			get { return GetColumnValue<DateTime?>(Columns.Ngaycapnhap); }
			set { SetColumnValue(Columns.Ngaycapnhap, value); }
		}
		  
		[XmlAttribute("MaTk")]
		[Bindable(true)]
		public int? MaTk 
		{
			get { return GetColumnValue<int?>(Columns.MaTk); }
			set { SetColumnValue(Columns.MaTk, value); }
		}
		  
		[XmlAttribute("Status")]
		[Bindable(true)]
		public string Status 
		{
			get { return GetColumnValue<string>(Columns.Status); }
			set { SetColumnValue(Columns.Status, value); }
		}
		
		#endregion
		
		
		#region PrimaryKey Methods		
		
        protected override void SetPrimaryKey(object oValue)
        {
            base.SetPrimaryKey(oValue);
            
            SetPKValues();
        }
        
		
		public CuaHangDAL.DanHMucCollection DanHMucRecords()
		{
			return new CuaHangDAL.DanHMucCollection().Where(DanHMuc.Columns.MaNVchinhsua, MaNV).Load();
		}
		public CuaHangDAL.HdCollection HdRecords()
		{
			return new CuaHangDAL.HdCollection().Where(Hd.Columns.MaNV, MaNV).Load();
		}
		public CuaHangDAL.KhachHangCollection KhachHangRecords()
		{
			return new CuaHangDAL.KhachHangCollection().Where(KhachHang.Columns.MaNVchinhsua, MaNV).Load();
		}
		public CuaHangDAL.LoaiThanhVienCollection LoaiThanhVienRecords()
		{
			return new CuaHangDAL.LoaiThanhVienCollection().Where(LoaiThanhVien.Columns.MaNVchinhsua, MaNV).Load();
		}
		public CuaHangDAL.NhaCungCapCollection NhaCungCapRecords()
		{
			return new CuaHangDAL.NhaCungCapCollection().Where(NhaCungCap.Columns.MaNVchinhsua, MaNV).Load();
		}
		public CuaHangDAL.NhanVienCollection ChildNhanVienRecords()
		{
			return new CuaHangDAL.NhanVienCollection().Where(NhanVien.Columns.MaNVchinhsua, MaNV).Load();
		}
		public CuaHangDAL.PnCollection PnRecords()
		{
			return new CuaHangDAL.PnCollection().Where(Pn.Columns.MaNV, MaNV).Load();
		}
		public CuaHangDAL.SanPhamCollection SanPhamRecords()
		{
			return new CuaHangDAL.SanPhamCollection().Where(SanPham.Columns.MaNVchinhsua, MaNV).Load();
		}
		#endregion
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a NhanVien ActiveRecord object related to this NhanVien
		/// 
		/// </summary>
		public CuaHangDAL.NhanVien ParentNhanVien
		{
			get { return CuaHangDAL.NhanVien.FetchByID(this.MaNVchinhsua); }
			set { SetColumnValue("MaNVchinhsua", value.MaNV); }
		}
		
		
		/// <summary>
		/// Returns a TaiKhoan ActiveRecord object related to this NhanVien
		/// 
		/// </summary>
		public CuaHangDAL.TaiKhoan TaiKhoan
		{
			get { return CuaHangDAL.TaiKhoan.FetchByID(this.MaTk); }
			set { SetColumnValue("MaTk", value.MaTK); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varTenNv,string varDiaChi,string varSdt,string varEmail,string varCmd,decimal? varThamsoloinhuan,int? varMaNVchinhsua,DateTime? varNgaycapnhap,int? varMaTk,string varStatus)
		{
			NhanVien item = new NhanVien();
			
			item.TenNv = varTenNv;
			
			item.DiaChi = varDiaChi;
			
			item.Sdt = varSdt;
			
			item.Email = varEmail;
			
			item.Cmd = varCmd;
			
			item.Thamsoloinhuan = varThamsoloinhuan;
			
			item.MaNVchinhsua = varMaNVchinhsua;
			
			item.Ngaycapnhap = varNgaycapnhap;
			
			item.MaTk = varMaTk;
			
			item.Status = varStatus;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varMaNV,string varTenNv,string varDiaChi,string varSdt,string varEmail,string varCmd,decimal? varThamsoloinhuan,int? varMaNVchinhsua,DateTime? varNgaycapnhap,int? varMaTk,string varStatus)
		{
			NhanVien item = new NhanVien();
			
				item.MaNV = varMaNV;
			
				item.TenNv = varTenNv;
			
				item.DiaChi = varDiaChi;
			
				item.Sdt = varSdt;
			
				item.Email = varEmail;
			
				item.Cmd = varCmd;
			
				item.Thamsoloinhuan = varThamsoloinhuan;
			
				item.MaNVchinhsua = varMaNVchinhsua;
			
				item.Ngaycapnhap = varNgaycapnhap;
			
				item.MaTk = varMaTk;
			
				item.Status = varStatus;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn MaNVColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn TenNvColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn DiaChiColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn SdtColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn EmailColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn CmdColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn ThamsoloinhuanColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn MaNVchinhsuaColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn NgaycapnhapColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn MaTkColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn StatusColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string MaNV = @"MaNV";
			 public static string TenNv = @"TenNv";
			 public static string DiaChi = @"DiaChi";
			 public static string Sdt = @"sdt";
			 public static string Email = @"Email";
			 public static string Cmd = @"CMD";
			 public static string Thamsoloinhuan = @"thamsoloinhuan";
			 public static string MaNVchinhsua = @"MaNVchinhsua";
			 public static string Ngaycapnhap = @"ngaycapnhap";
			 public static string MaTk = @"MaTk";
			 public static string Status = @"status";
						
		}
		#endregion
		
		#region Update PK Collections
		
        public void SetPKValues()
        {
}
        #endregion
    
        #region Deep Save
		
        public void DeepSave()
        {
            Save();
            
}
        #endregion
	}
}
