using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CuaHangDAL
{
    /// <summary>
    /// Controller class for NhanVien
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class NhanVienController
    {
        // Preload our schema..
        NhanVien thisSchemaLoad = new NhanVien();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public NhanVienCollection FetchAll()
        {
            NhanVienCollection coll = new NhanVienCollection();
            Query qry = new Query(NhanVien.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public NhanVienCollection FetchByID(object MaNV)
        {
            NhanVienCollection coll = new NhanVienCollection().Where("MaNV", MaNV).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public NhanVienCollection FetchByQuery(Query qry)
        {
            NhanVienCollection coll = new NhanVienCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MaNV)
        {
            return (NhanVien.Delete(MaNV) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MaNV)
        {
            return (NhanVien.Destroy(MaNV) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public NhanVien Insert(NhanVien item)
	    {
		    
        
	    
		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public NhanVien Update(NhanVien item2)
	    {
		    NhanVien item = new NhanVien();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.MaNV = item2.MaNV;
				
			item.TenNv = item2.TenNv;
				
			item.DiaChi = item2.DiaChi;
				
			item.Sdt = item2.Sdt;
				
			item.Email = item2.Email;
				
			item.Cmd = item2.Cmd;
				
			item.Thamsoloinhuan = item2.Thamsoloinhuan;
				
			item.MaNVchinhsua = item2.MaNVchinhsua;
				
			item.Ngaycapnhap = item2.Ngaycapnhap;
				
			item.MaTk = item2.MaTk;
				
			item.Status = item2.Status;
				
	        item.Save(UserName);
            return item;
	    }
    }
}
