using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CuaHangDAL
{
    /// <summary>
    /// Controller class for PN
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class PnController
    {
        // Preload our schema..
        Pn thisSchemaLoad = new Pn();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public PnCollection FetchAll()
        {
            PnCollection coll = new PnCollection();
            Query qry = new Query(Pn.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public PnCollection FetchByID(object MaPN)
        {
            PnCollection coll = new PnCollection().Where("MaPN", MaPN).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public PnCollection FetchByQuery(Query qry)
        {
            PnCollection coll = new PnCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MaPN)
        {
            return (Pn.Delete(MaPN) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MaPN)
        {
            return (Pn.Destroy(MaPN) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public Pn Insert(Pn item)
	    {

		    item.Save(UserName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public Pn Update(Pn item2)
	    {
		    Pn item = new Pn();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.MaPN = item2.MaPN;
				
			item.NgayNhap = item2.NgayNhap;
				
			item.MaNCC = item2.MaNCC;
				
			item.MaNV = item2.MaNV;
				
			item.Status = item2.Status;
				
	        item.Save(UserName);
            return item;
	    }
    }
}
