using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CuaHangDAL{
    public partial class SPs{
        
        /// <summary>
        /// Creates an object wrapper for the tinhgiatatcaSP Procedure
        /// </summary>
        public static StoredProcedure TinhgiatatcaSP(int? masp)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("tinhgiatatcaSP", DataService.GetInstance("AdventureWorks"), "dbo");
        	
            sp.Command.AddParameter("@masp", masp, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
    }
    
}
