using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace CuaHangDAL{
    public partial class SPs{

        public static StoredProcedure Timkiem(string tensp, double? gianhap, int? madanhmuc)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("timkiem", DataService.GetInstance("AdventureWorks"), "dbo");

            sp.Command.AddParameter("@tensp", tensp, DbType.String, null, null);

            sp.Command.AddParameter("@gianhap", gianhap, DbType.Double, null, 53);

            sp.Command.AddParameter("@madanhmuc", madanhmuc, DbType.Int32, 0, 10);

            return sp;
        }


    }

}
